import type { OrgRole, ProjectRole } from "@prisma/client";
import type { Permission } from "./permissions.js";
import { Permissions } from "./permissions.js";

const ROLE_PERMISSIONS: Record<OrgRole, Set<Permission>> = {
  ADMIN: new Set([
    Permissions.ORGANIZATION_READ,
    Permissions.ORGANIZATION_UPDATE,
    Permissions.ORGANIZATION_MANAGE_MEMBERS,
    Permissions.USER_READ,
    Permissions.USER_UPDATE,
    Permissions.USER_UPDATE_OWN,
    // Project permissions for org admins
    Permissions.PROJECT_CREATE,
    Permissions.PROJECT_READ,
    Permissions.PROJECT_UPDATE,
    Permissions.PROJECT_DELETE,
    Permissions.PROJECT_MANAGE_MEMBERS,
    // Estimate permissions
    Permissions.ESTIMATE_CREATE,
    Permissions.ESTIMATE_READ,
    Permissions.ESTIMATE_UPDATE,
    Permissions.ESTIMATE_DELETE,
    Permissions.ESTIMATE_APPROVE,
    // Phase 5: Subcontractors & Procurement
    Permissions.SUBCONTRACTOR_CREATE,
    Permissions.SUBCONTRACTOR_READ,
    Permissions.SUBCONTRACTOR_UPDATE,
    Permissions.SUBCONTRACTOR_DELETE,
    Permissions.VENDOR_CREATE,
    Permissions.VENDOR_READ,
    Permissions.VENDOR_UPDATE,
    Permissions.VENDOR_DELETE,
    Permissions.MATERIAL_CREATE,
    Permissions.MATERIAL_READ,
    Permissions.MATERIAL_UPDATE,
    Permissions.MATERIAL_REQUEST_CREATE,
    Permissions.MATERIAL_REQUEST_READ,
    Permissions.MATERIAL_REQUEST_UPDATE,
    Permissions.MATERIAL_REQUEST_APPROVE,
    Permissions.PURCHASE_ORDER_CREATE,
    Permissions.PURCHASE_ORDER_READ,
    Permissions.PURCHASE_ORDER_UPDATE,
    Permissions.PURCHASE_ORDER_APPROVE,
    Permissions.DELIVERY_CREATE,
    Permissions.DELIVERY_READ,
    Permissions.DELIVERY_UPDATE,
    Permissions.INVENTORY_READ,
    Permissions.INVENTORY_TRANSACT,
    // Phase 6: Documents, RFIs, Submittals, Quality, Safety, Compliance
    Permissions.DOCUMENT_CREATE,
    Permissions.DOCUMENT_READ,
    Permissions.DOCUMENT_UPDATE,
    Permissions.DOCUMENT_DELETE,
    Permissions.DOCUMENT_LINK,
    Permissions.RFI_CREATE,
    Permissions.RFI_READ,
    Permissions.RFI_UPDATE,
    Permissions.RFI_ANSWER,
    Permissions.RFI_CLOSE,
    Permissions.SUBMITTAL_CREATE,
    Permissions.SUBMITTAL_READ,
    Permissions.SUBMITTAL_REVIEW,
    Permissions.SUBMITTAL_APPROVE,
    Permissions.INSPECTION_SCHEDULE,
    Permissions.INSPECTION_READ,
    Permissions.INSPECTION_RECORD,
    Permissions.DEFICIENCY_RESOLVE,
    Permissions.SAFETY_REPORT,
    Permissions.SAFETY_READ,
    Permissions.SAFETY_INVESTIGATE,
    Permissions.COMPLIANCE_CREATE,
    Permissions.COMPLIANCE_READ,
    Permissions.COMPLIANCE_UPDATE,
    // Phase 7: Commercial Control
    Permissions.BUDGET_MANAGE,
    Permissions.COST_TRANSACTION_CREATE,
    Permissions.COST_TRANSACTION_READ,
    Permissions.CHANGE_ORDER_CREATE,
    Permissions.CHANGE_ORDER_READ,
    Permissions.CHANGE_ORDER_APPROVE,
    Permissions.SOV_MANAGE,
    Permissions.SOV_READ,
    Permissions.PAYMENT_APPLICATION_CREATE,
    Permissions.PAYMENT_APPLICATION_READ,
    Permissions.PAYMENT_APPLICATION_APPROVE,
    Permissions.INVOICE_CREATE,
    Permissions.INVOICE_READ,
    Permissions.INVOICE_APPROVE,
    Permissions.PAYMENT_RECORD,
    Permissions.PAYMENT_READ,
    Permissions.PAYMENT_APPROVE,
    Permissions.RETAINAGE_RELEASE,
    Permissions.COMMERCIAL_OVERVIEW_READ,
    // Phase 8: Notifications
    Permissions.NOTIFICATION_READ,
    Permissions.NOTIFICATION_MANAGE,
    // Phase 9: Reporting
    Permissions.REPORT_PROJECT_READ,
    Permissions.REPORT_ORG_READ,
  ]),
  MEMBER: new Set([
    Permissions.ORGANIZATION_READ,
    Permissions.USER_READ,
    Permissions.USER_UPDATE_OWN,
    Permissions.PROJECT_READ,
    Permissions.ESTIMATE_READ,
    Permissions.SUBCONTRACTOR_READ,
    Permissions.VENDOR_READ,
    Permissions.MATERIAL_READ,
    Permissions.MATERIAL_REQUEST_READ,
    Permissions.PURCHASE_ORDER_READ,
    Permissions.DELIVERY_READ,
    Permissions.INVENTORY_READ,
    // Phase 6 reads
    Permissions.DOCUMENT_READ,
    Permissions.RFI_READ,
    Permissions.SUBMITTAL_READ,
    Permissions.INSPECTION_READ,
    Permissions.SAFETY_READ,
    Permissions.COMPLIANCE_READ,
    // Phase 7 reads
    Permissions.COST_TRANSACTION_READ,
    Permissions.CHANGE_ORDER_READ,
    Permissions.SOV_READ,
    Permissions.PAYMENT_APPLICATION_READ,
    Permissions.INVOICE_READ,
    Permissions.PAYMENT_READ,
    Permissions.COMMERCIAL_OVERVIEW_READ,
    // Phase 8: Notifications
    Permissions.NOTIFICATION_READ,
    Permissions.NOTIFICATION_MANAGE,
    // Phase 9: Reporting
    Permissions.REPORT_PROJECT_READ,
    Permissions.REPORT_ORG_READ,
  ]),
  BILLING: new Set([
    Permissions.ORGANIZATION_READ,
    Permissions.USER_READ,
    Permissions.USER_UPDATE_OWN,
    Permissions.PROJECT_READ,
    Permissions.ESTIMATE_READ,
    Permissions.ESTIMATE_APPROVE,
    // Phase 7 billing
    Permissions.INVOICE_READ,
    Permissions.PAYMENT_READ,
    Permissions.COMMERCIAL_OVERVIEW_READ,
    // Phase 8: Notifications
    Permissions.NOTIFICATION_READ,
    Permissions.NOTIFICATION_MANAGE,
    // Phase 9: Reporting
    Permissions.REPORT_PROJECT_READ,
    Permissions.REPORT_ORG_READ,
  ]),
};

const PROJECT_ROLE_PERMISSIONS: Record<ProjectRole, Set<Permission>> = {
  PROJECT_MANAGER: new Set([
    Permissions.PROJECT_READ,
    Permissions.PROJECT_UPDATE,
    Permissions.PROJECT_MANAGE_MEMBERS,
    Permissions.TASK_CREATE,
    Permissions.TASK_UPDATE,
    Permissions.DOCUMENT_READ,
    Permissions.DOCUMENT_UPLOAD,
    Permissions.CHANGE_ORDER_APPROVE,
    // Procurement & Subcontractor PM permissions
    Permissions.SUBCONTRACTOR_CREATE,
    Permissions.SUBCONTRACTOR_READ,
    Permissions.SUBCONTRACTOR_UPDATE,
    Permissions.VENDOR_READ,
    Permissions.MATERIAL_READ,
    Permissions.MATERIAL_REQUEST_CREATE,
    Permissions.MATERIAL_REQUEST_READ,
    Permissions.MATERIAL_REQUEST_UPDATE,
    Permissions.MATERIAL_REQUEST_APPROVE,
    Permissions.PURCHASE_ORDER_CREATE,
    Permissions.PURCHASE_ORDER_READ,
    Permissions.PURCHASE_ORDER_UPDATE,
    Permissions.PURCHASE_ORDER_APPROVE,
    Permissions.DELIVERY_CREATE,
    Permissions.DELIVERY_READ,
    Permissions.DELIVERY_UPDATE,
    Permissions.INVENTORY_READ,
    Permissions.INVENTORY_TRANSACT,
    // Phase 6 PM permissions
    Permissions.DOCUMENT_CREATE,
    Permissions.DOCUMENT_UPDATE,
    Permissions.DOCUMENT_DELETE,
    Permissions.DOCUMENT_LINK,
    Permissions.RFI_CREATE,
    Permissions.RFI_READ,
    Permissions.RFI_UPDATE,
    Permissions.RFI_ANSWER,
    Permissions.RFI_CLOSE,
    Permissions.SUBMITTAL_CREATE,
    Permissions.SUBMITTAL_READ,
    Permissions.SUBMITTAL_REVIEW,
    Permissions.SUBMITTAL_APPROVE,
    Permissions.INSPECTION_SCHEDULE,
    Permissions.INSPECTION_READ,
    Permissions.INSPECTION_RECORD,
    Permissions.DEFICIENCY_RESOLVE,
    Permissions.SAFETY_REPORT,
    Permissions.SAFETY_READ,
    Permissions.SAFETY_INVESTIGATE,
    Permissions.COMPLIANCE_CREATE,
    Permissions.COMPLIANCE_READ,
    Permissions.COMPLIANCE_UPDATE,
    // Phase 7 PM permissions
    Permissions.BUDGET_MANAGE,
    Permissions.COST_TRANSACTION_CREATE,
    Permissions.COST_TRANSACTION_READ,
    Permissions.CHANGE_ORDER_CREATE,
    Permissions.CHANGE_ORDER_READ,
    Permissions.SOV_MANAGE,
    Permissions.SOV_READ,
    Permissions.PAYMENT_APPLICATION_CREATE,
    Permissions.PAYMENT_APPLICATION_READ,
    Permissions.INVOICE_CREATE,
    Permissions.INVOICE_READ,
    Permissions.COMMERCIAL_OVERVIEW_READ,
    // Phase 8: Notifications
    Permissions.NOTIFICATION_READ,
    Permissions.NOTIFICATION_MANAGE,
    // Phase 9: Reporting
    Permissions.REPORT_PROJECT_READ,
    Permissions.REPORT_ORG_READ,
  ]),
  FINANCE: new Set([
    Permissions.PROJECT_READ,
    Permissions.TASK_UPDATE_OWN,
    Permissions.DOCUMENT_READ,
    Permissions.PAYMENT_APPROVE,
    Permissions.PURCHASE_ORDER_READ,
    Permissions.PURCHASE_ORDER_APPROVE,
    Permissions.SUBCONTRACTOR_READ,
    // Phase 7 Finance permissions
    Permissions.BUDGET_MANAGE,
    Permissions.COST_TRANSACTION_CREATE,
    Permissions.COST_TRANSACTION_READ,
    Permissions.CHANGE_ORDER_READ,
    Permissions.CHANGE_ORDER_APPROVE,
    Permissions.SOV_READ,
    Permissions.PAYMENT_APPLICATION_READ,
    Permissions.PAYMENT_APPLICATION_APPROVE,
    Permissions.INVOICE_READ,
    Permissions.INVOICE_APPROVE,
    Permissions.PAYMENT_RECORD,
    Permissions.PAYMENT_READ,
    Permissions.RETAINAGE_RELEASE,
    Permissions.COMMERCIAL_OVERVIEW_READ,
    // Phase 8: Notifications
    Permissions.NOTIFICATION_READ,
    Permissions.NOTIFICATION_MANAGE,
    // Phase 9: Reporting
    Permissions.REPORT_PROJECT_READ,
    Permissions.REPORT_ORG_READ,
  ]),
  PROCUREMENT: new Set([
    Permissions.PROJECT_READ,
    Permissions.TASK_CREATE,
    Permissions.TASK_UPDATE_OWN,
    Permissions.DOCUMENT_READ,
    Permissions.DOCUMENT_UPLOAD,
    Permissions.VENDOR_CREATE,
    Permissions.VENDOR_READ,
    Permissions.VENDOR_UPDATE,
    Permissions.MATERIAL_CREATE,
    Permissions.MATERIAL_READ,
    Permissions.MATERIAL_UPDATE,
    Permissions.MATERIAL_REQUEST_CREATE,
    Permissions.MATERIAL_REQUEST_READ,
    Permissions.MATERIAL_REQUEST_UPDATE,
    Permissions.MATERIAL_REQUEST_APPROVE,
    Permissions.PURCHASE_ORDER_CREATE,
    Permissions.PURCHASE_ORDER_READ,
    Permissions.PURCHASE_ORDER_UPDATE,
    Permissions.DELIVERY_CREATE,
    Permissions.DELIVERY_READ,
    Permissions.DELIVERY_UPDATE,
    Permissions.INVENTORY_READ,
    Permissions.INVENTORY_TRANSACT,
    // Phase 7 Procurement
    Permissions.COST_TRANSACTION_READ,
    Permissions.INVOICE_READ,
    Permissions.COMMERCIAL_OVERVIEW_READ,
    // Phase 8: Notifications
    Permissions.NOTIFICATION_READ,
    Permissions.NOTIFICATION_MANAGE,
    // Phase 9: Reporting
    Permissions.REPORT_PROJECT_READ,
  ]),
  SITE_SUPERVISOR: new Set([
    Permissions.PROJECT_READ,
    Permissions.TASK_CREATE,
    Permissions.TASK_UPDATE,
    Permissions.DOCUMENT_READ,
    Permissions.DOCUMENT_UPLOAD,
    Permissions.MATERIAL_READ,
    Permissions.MATERIAL_REQUEST_CREATE,
    Permissions.MATERIAL_REQUEST_READ,
    Permissions.PURCHASE_ORDER_READ,
    Permissions.DELIVERY_READ,
    Permissions.DELIVERY_UPDATE,
    Permissions.INVENTORY_READ,
    Permissions.INVENTORY_TRANSACT,
    Permissions.SUBCONTRACTOR_READ,
    // Phase 6 Site Supervisor permissions
    Permissions.DOCUMENT_CREATE,
    Permissions.DOCUMENT_LINK,
    Permissions.RFI_CREATE,
    Permissions.RFI_READ,
    Permissions.SUBMITTAL_READ,
    Permissions.INSPECTION_SCHEDULE,
    Permissions.INSPECTION_READ,
    Permissions.INSPECTION_RECORD,
    Permissions.DEFICIENCY_RESOLVE,
    Permissions.SAFETY_REPORT,
    Permissions.SAFETY_READ,
    // Phase 7 Site Supervisor
    Permissions.COST_TRANSACTION_CREATE,
    Permissions.COST_TRANSACTION_READ,
    Permissions.CHANGE_ORDER_READ,
    // Phase 8: Notifications
    Permissions.NOTIFICATION_READ,
    Permissions.NOTIFICATION_MANAGE,
    // Phase 9: Reporting
    Permissions.REPORT_PROJECT_READ,
  ]),
  SUBCONTRACTOR: new Set([
    Permissions.PROJECT_READ,
    Permissions.TASK_UPDATE_OWN,
    Permissions.DOCUMENT_READ,
    Permissions.SUBCONTRACTOR_READ,
    Permissions.MATERIAL_READ,
    Permissions.DELIVERY_READ,
    Permissions.INVENTORY_READ,
    // Phase 6 Subcontractor permissions
    Permissions.SUBMITTAL_CREATE,
    Permissions.SUBMITTAL_READ,
    Permissions.RFI_READ,
    Permissions.DEFICIENCY_RESOLVE,
    // Phase 7 Subcontractor permissions
    Permissions.PAYMENT_APPLICATION_CREATE,
    Permissions.PAYMENT_APPLICATION_READ,
    Permissions.INVOICE_CREATE,
    Permissions.INVOICE_READ,
    Permissions.CHANGE_ORDER_READ,
    // Phase 8: Notifications
    Permissions.NOTIFICATION_READ,
    Permissions.NOTIFICATION_MANAGE,
  ]),
  CLIENT: new Set([
    Permissions.PROJECT_READ,
    Permissions.DOCUMENT_READ,
    Permissions.RFI_READ,
    Permissions.INSPECTION_READ,
    // Phase 7 Client permissions
    Permissions.CHANGE_ORDER_APPROVE,
    Permissions.PAYMENT_APPLICATION_APPROVE,
    Permissions.SOV_READ,
    Permissions.PAYMENT_APPLICATION_READ,
    Permissions.INVOICE_READ,
    Permissions.COMMERCIAL_OVERVIEW_READ,
    // Phase 8: Notifications
    Permissions.NOTIFICATION_READ,
    Permissions.NOTIFICATION_MANAGE,
    // Phase 9: Reporting
    Permissions.REPORT_PROJECT_READ,
  ]),
  VIEWER: new Set([Permissions.PROJECT_READ, Permissions.DOCUMENT_READ, Permissions.COMMERCIAL_OVERVIEW_READ,
    // Phase 8: Notifications
    Permissions.NOTIFICATION_READ,
    Permissions.NOTIFICATION_MANAGE,
  ]),
};

export function hasPermission(role: OrgRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.has(permission) ?? false;
}

export function hasProjectPermission(role: ProjectRole, permission: Permission): boolean {
  return PROJECT_ROLE_PERMISSIONS[role]?.has(permission) ?? false;
}
