import type { OrgRole, ProjectRole } from "@prisma/client";
import type { Permission } from "./permissions.js";
import { Permissions } from "./permissions.js";

const ROLE_PERMISSIONS: Record<OrgRole, Set<Permission>> = {
  ADMIN: new Set([
    Permissions.ORGANIZATION_READ,
    Permissions.ORGANIZATION_UPDATE,
    Permissions.ORGANIZATION_MANAGE_MEMBERS,
    Permissions.USER_READ,
    Permissions.USER_UPDATE,
    Permissions.USER_UPDATE_OWN,
    // Project permissions for org admins
    Permissions.PROJECT_CREATE,
    Permissions.PROJECT_READ,
    Permissions.PROJECT_UPDATE,
    Permissions.PROJECT_DELETE,
    Permissions.PROJECT_MANAGE_MEMBERS,
    // Estimate permissions
    Permissions.ESTIMATE_CREATE,
    Permissions.ESTIMATE_READ,
    Permissions.ESTIMATE_UPDATE,
    Permissions.ESTIMATE_DELETE,
    Permissions.ESTIMATE_APPROVE,
    // Phase 5: Subcontractors & Procurement
    Permissions.SUBCONTRACTOR_CREATE,
    Permissions.SUBCONTRACTOR_READ,
    Permissions.SUBCONTRACTOR_UPDATE,
    Permissions.SUBCONTRACTOR_DELETE,
    Permissions.VENDOR_CREATE,
    Permissions.VENDOR_READ,
    Permissions.VENDOR_UPDATE,
    Permissions.VENDOR_DELETE,
    Permissions.MATERIAL_CREATE,
    Permissions.MATERIAL_READ,
    Permissions.MATERIAL_UPDATE,
    Permissions.MATERIAL_REQUEST_CREATE,
    Permissions.MATERIAL_REQUEST_READ,
    Permissions.MATERIAL_REQUEST_UPDATE,
    Permissions.MATERIAL_REQUEST_APPROVE,
    Permissions.PURCHASE_ORDER_CREATE,
    Permissions.PURCHASE_ORDER_READ,
    Permissions.PURCHASE_ORDER_UPDATE,
    Permissions.PURCHASE_ORDER_APPROVE,
    Permissions.DELIVERY_CREATE,
    Permissions.DELIVERY_READ,
    Permissions.DELIVERY_UPDATE,
    Permissions.INVENTORY_READ,
    Permissions.INVENTORY_TRANSACT,
  ]),
  MEMBER: new Set([
    Permissions.ORGANIZATION_READ,
    Permissions.USER_READ,
    Permissions.USER_UPDATE_OWN,
    Permissions.PROJECT_READ,
    Permissions.ESTIMATE_READ,
    Permissions.SUBCONTRACTOR_READ,
    Permissions.VENDOR_READ,
    Permissions.MATERIAL_READ,
    Permissions.MATERIAL_REQUEST_READ,
    Permissions.PURCHASE_ORDER_READ,
    Permissions.DELIVERY_READ,
    Permissions.INVENTORY_READ,
  ]),
  BILLING: new Set([
    Permissions.ORGANIZATION_READ,
    Permissions.USER_READ,
    Permissions.USER_UPDATE_OWN,
    Permissions.PROJECT_READ,
    Permissions.ESTIMATE_READ,
    Permissions.ESTIMATE_APPROVE,
  ]),
};

const PROJECT_ROLE_PERMISSIONS: Record<ProjectRole, Set<Permission>> = {
  PROJECT_MANAGER: new Set([
    Permissions.PROJECT_READ,
    Permissions.PROJECT_UPDATE,
    Permissions.PROJECT_MANAGE_MEMBERS,
    Permissions.TASK_CREATE,
    Permissions.TASK_UPDATE,
    Permissions.DOCUMENT_READ,
    Permissions.DOCUMENT_UPLOAD,
    Permissions.CHANGE_ORDER_APPROVE,
    // Procurement & Subcontractor PM permissions
    Permissions.SUBCONTRACTOR_CREATE,
    Permissions.SUBCONTRACTOR_READ,
    Permissions.SUBCONTRACTOR_UPDATE,
    Permissions.VENDOR_READ,
    Permissions.MATERIAL_READ,
    Permissions.MATERIAL_REQUEST_CREATE,
    Permissions.MATERIAL_REQUEST_READ,
    Permissions.MATERIAL_REQUEST_UPDATE,
    Permissions.MATERIAL_REQUEST_APPROVE,
    Permissions.PURCHASE_ORDER_CREATE,
    Permissions.PURCHASE_ORDER_READ,
    Permissions.PURCHASE_ORDER_UPDATE,
    Permissions.PURCHASE_ORDER_APPROVE,
    Permissions.DELIVERY_CREATE,
    Permissions.DELIVERY_READ,
    Permissions.DELIVERY_UPDATE,
    Permissions.INVENTORY_READ,
    Permissions.INVENTORY_TRANSACT,
  ]),
  FINANCE: new Set([
    Permissions.PROJECT_READ,
    Permissions.TASK_UPDATE_OWN,
    Permissions.DOCUMENT_READ,
    Permissions.PAYMENT_APPROVE,
    Permissions.PURCHASE_ORDER_READ,
    Permissions.PURCHASE_ORDER_APPROVE,
    Permissions.SUBCONTRACTOR_READ,
  ]),
  PROCUREMENT: new Set([
    Permissions.PROJECT_READ,
    Permissions.TASK_CREATE,
    Permissions.TASK_UPDATE_OWN,
    Permissions.DOCUMENT_READ,
    Permissions.DOCUMENT_UPLOAD,
    Permissions.VENDOR_CREATE,
    Permissions.VENDOR_READ,
    Permissions.VENDOR_UPDATE,
    Permissions.MATERIAL_CREATE,
    Permissions.MATERIAL_READ,
    Permissions.MATERIAL_UPDATE,
    Permissions.MATERIAL_REQUEST_CREATE,
    Permissions.MATERIAL_REQUEST_READ,
    Permissions.MATERIAL_REQUEST_UPDATE,
    Permissions.MATERIAL_REQUEST_APPROVE,
    Permissions.PURCHASE_ORDER_CREATE,
    Permissions.PURCHASE_ORDER_READ,
    Permissions.PURCHASE_ORDER_UPDATE,
    Permissions.DELIVERY_CREATE,
    Permissions.DELIVERY_READ,
    Permissions.DELIVERY_UPDATE,
    Permissions.INVENTORY_READ,
    Permissions.INVENTORY_TRANSACT,
  ]),
  SITE_SUPERVISOR: new Set([
    Permissions.PROJECT_READ,
    Permissions.TASK_CREATE,
    Permissions.TASK_UPDATE,
    Permissions.DOCUMENT_READ,
    Permissions.DOCUMENT_UPLOAD,
    Permissions.MATERIAL_READ,
    Permissions.MATERIAL_REQUEST_CREATE,
    Permissions.MATERIAL_REQUEST_READ,
    Permissions.PURCHASE_ORDER_READ,
    Permissions.DELIVERY_READ,
    Permissions.DELIVERY_UPDATE,
    Permissions.INVENTORY_READ,
    Permissions.INVENTORY_TRANSACT,
    Permissions.SUBCONTRACTOR_READ,
  ]),
  SUBCONTRACTOR: new Set([
    Permissions.PROJECT_READ,
    Permissions.TASK_UPDATE_OWN,
    Permissions.DOCUMENT_READ,
    Permissions.SUBCONTRACTOR_READ,
    Permissions.MATERIAL_READ,
    Permissions.DELIVERY_READ,
    Permissions.INVENTORY_READ,
  ]),
  CLIENT: new Set([Permissions.PROJECT_READ, Permissions.DOCUMENT_READ]),
  VIEWER: new Set([Permissions.PROJECT_READ, Permissions.DOCUMENT_READ]),
};

export function hasPermission(role: OrgRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.has(permission) ?? false;
}

export function hasProjectPermission(role: ProjectRole, permission: Permission): boolean {
  return PROJECT_ROLE_PERMISSIONS[role]?.has(permission) ?? false;
}
