import type { ProjectStatus } from "@prisma/client";

export const STATUS_TRANSITIONS: Record<ProjectStatus, ProjectStatus[]> = {
  DRAFT: ["ACTIVE", "CANCELLED"],
  ACTIVE: ["ON_HOLD", "COMPLETED", "CANCELLED"],
  ON_HOLD: ["ACTIVE", "CANCELLED"],
  COMPLETED: [],
  CANCELLED: [],
};

export const TERMINAL_STATUSES: ProjectStatus[] = ["COMPLETED", "CANCELLED"];

export const PROJECT_AUDIT_ACTIONS = {
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_STATUS_CHANGED: "PROJECT_STATUS_CHANGED",
  PROJECT_MEMBER_ADDED: "PROJECT_MEMBER_ADDED",
  PROJECT_MEMBER_REMOVED: "PROJECT_MEMBER_REMOVED",
  PROJECT_MEMBER_ROLE_CHANGED: "PROJECT_MEMBER_ROLE_CHANGED",
  PHASE_CREATED: "PHASE_CREATED",
  PHASE_UPDATED: "PHASE_UPDATED",
  PHASE_DELETED: "PHASE_DELETED",
  PHASES_REORDERED: "PHASES_REORDERED",
  COST_CODE_CREATED: "COST_CODE_CREATED",
  COST_CODE_UPDATED: "COST_CODE_UPDATED",
  COST_CODE_DEACTIVATED: "COST_CODE_DEACTIVATED",
  PROJECT_SETTINGS_UPDATED: "PROJECT_SETTINGS_UPDATED",
} as const;
