export const PROCUREMENT_AUDIT_ACTIONS = {
  VENDOR_CREATED: "VENDOR_CREATED",
  VENDOR_UPDATED: "VENDOR_UPDATED",
  VENDOR_STATUS_CHANGED: "VENDOR_STATUS_CHANGED",
  MATERIAL_CREATED: "MATERIAL_CREATED",
  MATERIAL_UPDATED: "MATERIAL_UPDATED",
  MATERIAL_REQUEST_CREATED: "MATERIAL_REQUEST_CREATED",
  MATERIAL_REQUEST_SUBMITTED: "MATERIAL_REQUEST_SUBMITTED",
  MATERIAL_REQUEST_APPROVED: "MATERIAL_REQUEST_APPROVED",
  MATERIAL_REQUEST_REJECTED: "MATERIAL_REQUEST_REJECTED",
  PURCHASE_ORDER_CREATED: "PURCHASE_ORDER_CREATED",
  PURCHASE_ORDER_ISSUED: "PURCHASE_ORDER_ISSUED",
  PURCHASE_ORDER_CANCELLED: "PURCHASE_ORDER_CANCELLED",
  DELIVERY_SCHEDULED: "DELIVERY_SCHEDULED",
  DELIVERY_DELAYED: "DELIVERY_DELAYED",
  DELIVERY_RECEIVED: "DELIVERY_RECEIVED",
  INVENTORY_TRANSACTED: "INVENTORY_TRANSACTED",
} as const;

export const PROCUREMENT_DOMAIN_EVENTS = {
  MATERIAL_ORDERED: "MaterialOrdered",
  MATERIAL_DELAYED: "MaterialDelayed",
  MATERIAL_DELIVERED: "MaterialDelivered",
} as const;
