export const QUEUES = {
  DOCUMENTS: "documents",
  COMPLIANCE: "compliance",
  COMMUNICATIONS: "project-communications",
  COMMERCIAL: "commercial",
  TASKS: "tasks",
} as const;

export const JOBS = {
  DOCUMENT_PROCESS: "DOCUMENT_PROCESS",
  CHECK_COMPLIANCE_EXPIRATIONS: "CHECK_COMPLIANCE_EXPIRATIONS",
  CHECK_OVERDUE_RFIS_AND_SUBMITTALS: "CHECK_OVERDUE_RFIS_AND_SUBMITTALS",
  CHECK_OVERDUE_INVOICES: "CHECK_OVERDUE_INVOICES",
  CHECK_PENDING_PAYMENT_APPLICATIONS: "CHECK_PENDING_PAYMENT_APPLICATIONS",
  CHECK_OVERDUE_TASKS: "CHECK_OVERDUE_TASKS",
} as const;
